version: '3.1'

services:
  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - hexagonal_data:/var/lib/postgresql/data

volumes:
  hexagonal_data: